In [2]:
import os
import gzip
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
#from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans
#from sklearn.metrics import adjusted_rand_score,v_measure_score

def load_mnist(path, kind='train'):
    labels_path = os.path.join(path,'%s-labels-idx1-ubyte.gz' % kind)
    images_path = os.path.join(path,'%s-images-idx3-ubyte.gz' % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels
X_train, y_train = load_mnist('D:/MachineLearning/data/fashion', kind='train')
X_test, y_test = load_mnist('D:/MachineLearning/data/fashion', kind='t10k')

In [3]:
X_train.shape
X_train = X_train/255.0

In [4]:
print(y_train)
print(y_test)

[9 0 0 ... 3 0 5]
[9 2 1 ... 8 1 5]


In [19]:
kmeans = KMeans(n_clusters=10,max_iter=300,algorithm="full",random_state=0)

In [22]:
clusters = kmeans.fit_predict(X_train)
print(clusters)

KeyboardInterrupt: 

In [28]:
#Calculating permuted indices
from scipy.stats import mode
def get_permuted_labels(clusters):
    labels = np.zeros_like(clusters)
    for i in range(10):
        mask = (clusters == i)
        labels[mask] = mode(y_train[mask])[0]
    return labels


In [32]:
from sklearn.metrics import accuracy_score
kmeans_labels = get_permuted_labels(clusters)
accuracy  = accuracy_score(y_train, kmeans_labels)
cm = confusion_matrix(y_train, kmeans_labels)
print(accuracy*100)
print(cm)

55.33166666666667
[[3404  201    0    0  167  593 1583    2   50    0]
 [ 236 5413    0    0   63  156  129    0    3    0]
 [ 115    9    0    0 3519  515 1787    1   54    0]
 [1684 3209    0    0   49  522  524    0   12    0]
 [ 873  154    0    0 3596  252 1081    0   44    0]
 [   2    1    0    0    0 3766   29 1444   17  741]
 [1053   62    0    0 1954  774 2071    6   79    1]
 [   0    0    0    0    0  508    0 4680    1  811]
 [  22   28    0    0  269  494  228  237 4650   72]
 [   2    2    0    0    1  170   38  164    4 5619]]
